/* This file must be compiled into a separate bundle and inlined at the top of the page */
import {EventTrap} from '../../eventtrap';

// TODO: have a more canonical list of events
window['__eventTrap__'] = new EventTrap(document.documentElement, [
    "auxclick",
    "blur",
    "change",
    "click",
    "compositionend",
    "compositionstart",
    "compositionupdate",
    "contextmenu",
    "copy",
    "cut",
    "dblclick",
    "dragend",
    "dragenter",
    "dragleave",
    "dragover",
    "dragstart",
    "drop",
    "error",
    "focus",
    "focusin",
    "focusout",
    "input",
    "keydown",
    "keypress",
    "keyup",
    "load",
    "mousedown",
    "mouseenter",
    "mouseleave",
    "mouseout",
    "mouseover",
    "mouseup",
    "pagehide",
    "pageshow",
    "paste",
    "pointerdown",
    "pointerup",
    "submit",
    "touchend",
    "touchmove",
    "touchstart",
    "visibilitychange",
    "wheel",
]);
